config/routes.rb
Voting::Application.routes.draw do
  
  devise_for :users

  #EDIT ME TO CHANGE ROOT URL
  root :to => 'polls#index'
  
  resources :reports
  
  resources :polls, :shallow => true do
    resources :questions, :shallow => true do
      resources :answers
    end
  end
  
  #for presenting a poll
  match 'polls/:id/present', :to => 'polls#present', :as => :poll_present
  
  #for viewing/manager an active poll
  match 'active_polls/:id', :to => 'active_polls#show', :as => :view_active_poll
  match 'active_polls/:id/next', :to => 'active_polls#next', :as => :next_active_poll
  match 'active_polls/:id/prev', :to => 'active_polls#prev', :as => :prev_active_poll
  
  match ':token/submit/:answer_id', :to => 'active_polls#clicker_submit', :as => :clicker_submit
  
  match ':token', :to => 'active_polls#clicker', :as => :clicker
  
  match 'polls/:id/sort', :to => 'polls#sort', :as => :poll_questions_sort
  
  match 'polls/:poll_id/questions/:q_id/add', :to => 'questions#add_to_poll', :as => :add_to_poll
  match 'polls/:poll_id/questions/:q_id/remove', :to => 'questions#remove_from_poll', :as => :remove_from_poll
  
  match 'active_polls/:id/end', :to => 'active_polls#end', :as => :end_poll  
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :pollquestions
  has_many :polls, :through => :pollquestions
  has_many :answers
  has_many :active_polls
  
  after_update :save_answers
  
  validates_presence_of :body, :message => "Question cannot be blank."
  validates_associated :answers
  
  def answer_attributes=(answer_attributes)
    answer_attributes.each do |attributes|
      if attributes[:id].blank?
        answers.build(attributes)
      else
        answer = answers.detect { |a| a.id == attributes[:id].to_i }
        answer.attributes = attributes
      end
    end
  end
  
  def save_answers
    answers.each do |a|
      if a.should_destroy?
        a.destroy
      else
        a.save(false) #ignore validation, is handled by a question
      end
    end
  end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js
  
  # GET questions
  def index
    @poll = Poll.find(params[:poll_id])
    @poll_questions = @poll.questions.all
    @remaining_questions = @questions - @poll_questions
  end

  # GET questions/1
  def show    
  end

  # GET polls/1/questions/new
  def new
    @poll = Poll.find(params[:poll_id])
    @question = @poll.questions.build
    
    @num_answers ||= 4
    
    @num_answers.times { |i|
      @question.answers.build
      @question.answers[i].id = i
    }
  end

  # GET polls/1/questions/1/edit
  def edit
    @num_answers ||= 4
  end

  # POST polls/1/questions
  def create
    @poll = Poll.find(params[:poll_id])
    @question = @poll.questions.create(params[:question])
    
    params[:correct].each_with_index do |q, i|
      if q.last == "1"
        @question.answers[i].correct = true
      end
    end
    
    if @question.save
      highest_weight = Pollquestion.find_all_by_poll_id(params[:poll_id]).max { |a, b| a.weight <=> b.weight }.weight + 1
      Pollquestion.find_by_poll_id_and_question_id(@poll.id, @question.id).update_attributes(:weight => highest_weight)
      redirect_to(poll_questions_path(@poll), :notice => 'Question was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT polls/1/questions/1
  def update
    if params[:poll]
      @destination = polls_path(params[:poll])
    else
      @destination = @question
    end
    
    if @question.update_attributes(params[:id])
      question = Question.find(params[:id])
      params[:correct].each_with_index do |q, i|
        if q.last == "1"
          question.answers[i].correct = true
        elsif q.last == "0"
          question.answers[i].correct = false
        end
        question.save
      end
      redirect_to(@destination, :notice => 'Question was successfully updated.')
    else
      render :action => "edit" 
    end
  end
  
  # PUT polls/1/questions/1/add
  def add_to_poll
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:q_id])
    @poll.questions << @question
    respond_with @poll, @question

  end
  
  # PUT polls/1/questions/1/remove
  def remove_from_poll
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:q_id]);
    @poll.questions.delete(@question)
    respond_with @poll, @question
  end
  
  # DELETE polls/1/questions/1
  def destroy
    @question.destroy
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def add_answer_link(name)
    link_to_function name, do |page|
      #page.insert_html :bottom, :answers, :partial => 'answer', :object => Answer.new
    end
  end
end

app/views/questions/_answer.html.erb
<%= fields_for "question[answer_attributes][]", answer do |a| %>
  <div class="answer">
    <%= a.label :body, "Answer" %>
    <%= a.text_field :body, :index => nil %>

    <%= a.check_box :correct, :name => "correct[#{index}]" %>
    <%= a.label :correct %>
    
    <% if answer.new_record? %>
      <%= link_to_function "remove", "$(this).parent('.answer').remove()" %>
    <% else %>
      <%= link_to_function "remove", "mark_for_destroy(this)" %>
      <%= a.hidden_field :should_destroy, :index => nil, :class => 'should_destroy' %>
      <%= a.hidden_field :id, :index => nil %>
    <% end %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_for([@poll, @question]) do |f| %>
<% if @question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

    <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= f.label :body, "Question" %>
    <%= f.text_field :body %>
  </div>
  
  <p>
  <!--<p><%= add_answer_link "Add an answer" %></p>-->
  </p>
  
  <div id="answers">
    <% (0..(@num_answers - 1)).each do |i| %>
      <%= render :partial => 'answer', :object => @question.answers[i], :locals => {:index => i} %>
    <% end %>
  </div>
  
  <div class="actions">
    <%= f.submit %> 
  </div>
<% end %>

app/views/questions/add_to_poll.js.erb
var question = $(".question-<%= @question.id %>").remove();
var question_link = $(".question-link", question);
var link = "<%= escape_javascript(link_to 'X', remove_from_poll_path(@poll.id, @question.id), :remote => true) %>";

$("a", question_link).remove();
$(question_link).append(link);

$("#poll-questions tbody").append(question);

app/views/questions/edit.html.erb
<% content_for :title do %>
  Editing question
<% end %>

<%= render 'form' %>

app/views/questions/index.html.erb
<% content_for :title do %>
  Add questions to "<%= @poll.title %>"
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'jquery.tablednd_0_5', 'questions' %>
<% end %>

<%= link_to 'Back to poll', poll_path(@poll) %>
<%= link_to 'New Question', new_poll_question_path %>

<div id="question-listing">
  <table class="question-index" id="poll-questions">
    <thead>
      <tr>
        <th class="question">Questions currently in "<%= @poll.title %>"</th>
        <th class="question-remove"></th>
      </tr>
    </thead>
    <tbody>
    <% @poll_questions.each do |q| %>
      <tr class="question-<%= q.id %>">
        <td class="question"><%= q.body %></td>
        <td class="question-link"><%= link_to 'X', remove_from_poll_path(@poll.id, q.id), :remote => true %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <table class="question-index" id="all-questions">
    <thead>
      <tr>
        <th class="question">Your Questions</th>
        <th class="question-add"></th>
      </tr>
    </thead>
    <tbody>
    <% @remaining_questions.each do |q| %>
      <tr class="question-<%= q.id %>">
        <td class="question"><%= q.body %></td>
        <td class="question-link"><%= link_to 'Add', add_to_poll_path(@poll.id, q.id), :remote => true %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/questions/new.html.erb
<% content_for :title do %>
  New question
<% end %>

<%= render 'form' %>

app/views/questions/new.js.erb
$('#answers').append('<%= escape_javascript(render :partial => "answer", :object => Answer.new ) %>');

app/views/questions/remove_from_poll.js.erb
var question = $(".question-<%= @question.id %>").remove();
var question_link = $(".question-link", question);
var link = "<%= escape_javascript(link_to 'Add', add_to_poll_path(@poll.id, @question.id), :remote => true) %>";

$("a", question_link).remove();
$(question_link).append(link);

$("#all-questions tbody").append(question);

app/views/questions/show.html.erb
<% content_for :title do %>
  Question: <%= @question.body %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<p>
  <h3>Title</h3>
  <%= @question.body %>
</p>

<p>
  <h3>Polls this question belongs to</h3>
  <% if @question.polls.empty? %>
    <small>none</small>
  <% else %>
    <ul>
      <% @question.polls.each do |p|%>
      	<li><%= p.title %></li>
    	<% end%>
	  </ul>
	<% end %>
</p>

<p>
  <h3>Multiple Choice Answers</h3>
  <% if @question.answers.exists? %>
    <ol>
      <% @question.answers.each do |a| %>
        <li>
          <%= a.body %>
          <% if a.correct %> 
            <span class="correct"> (correct answer) 
          <% end %>
        </li>
      <% end %>
    </ol>
  <% else %>
    <p><small>No answers for this question yet.</small></p>
  <% end %>
  <p>
    <%= link_to 'Add a new answer', new_question_answer_path(@question) %> | <%= link_to 'Edit question', edit_question_path() %>
  </p>
</p>