config/routes.rb
Voting::Application.routes.draw do
  
  devise_for :users

  #EDIT ME TO CHANGE ROOT URL
  root :to => 'polls#index'
  
  resources :reports
  
  resources :polls, :shallow => true do
    resources :questions, :shallow => true do
      resources :answers
    end
  end
  
  #for presenting a poll
  match 'polls/:id/present', :to => 'polls#present', :as => :poll_present
  
  #for viewing/manager an active poll
  match 'active_polls/:id', :to => 'active_polls#show', :as => :view_active_poll
  match 'active_polls/:id/next', :to => 'active_polls#next', :as => :next_active_poll
  match 'active_polls/:id/prev', :to => 'active_polls#prev', :as => :prev_active_poll
  
  match ':token/submit/:answer_id', :to => 'active_polls#clicker_submit', :as => :clicker_submit
  
  match ':token', :to => 'active_polls#clicker', :as => :clicker
  
  match 'polls/:id/sort', :to => 'polls#sort', :as => :poll_questions_sort
  
  match 'polls/:poll_id/questions/:q_id/add', :to => 'questions#add_to_poll', :as => :add_to_poll
  match 'polls/:poll_id/questions/:q_id/remove', :to => 'questions#remove_from_poll', :as => :remove_from_poll
  
  match 'active_polls/:id/end', :to => 'active_polls#end', :as => :end_poll  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  
  validates_presence_of :body, :message => "Answer cannot be blank."
  
  attr_accessor :should_destroy
  
  def should_destroy?
    should_destroy.to_i == 1
  end
  
  # returns the number of people that picked this answer for the report parameter
  def picked(report)
    report.answered_questions.find_all_by_answer_id(self.id).count
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController  
  # GET /question/1/answers
  def index
    @question = Questions.find(params[:question_id])
  end

  # GET /question/1/answers/1
  def show
    @answer = Answer.find(params[:id])
  end

  # GET /question/1/answers/new
  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build
  end

  # GET /question/1/answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /question/1/answers
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(params[:answer])
    
    # This looks hacky
    @answer.question_id = @question.id

    if @answer.save
      redirect_to(@answer.question, :notice => 'Answer was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /question/1/answers/1
  def update
    @answer = Answer.find(params[:id])

    if @answer.update_attributes(params[:answer])
      redirect_to(@answer.question, :notice => 'Answer was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /question/1/answers/1
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body, "Answer" %>
    <%= f.text_field :body %>

    <%= f.check_box :correct %>
    <%= f.label :correct %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<% content_for :title do %>
  Editing answer
<% end %>

<%= render 'form' %>

app/views/answers/index.html.erb
<% content_for :title do %>
  Listing answers
<% end %>

<table>
  <tr>
    <th>Body</th>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% if @answers.exists? %>
<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.body %></td>
    <td><%= answer.question %></td>
    <td><%= link_to 'Show', question_answer_path(answer) %></td>
    <td><%= link_to 'Edit', edit_question_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', question_answer_path(answer), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_question_answer_path %>

app/views/answers/new.html.erb
<% content_for :title do %>
  New answer
<% end %>

<%= render 'form' %>

app/views/answers/show.html.erb
<% content_for :title do %>
  Answer to question: <%= @answer.question.body %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<p>
  <h3>Body</h3>
  <%= @answer.body %>
  <% if @answer.correct %>
    <span class="correct"> (correct answer) </span>
  <% end %>
</p>

<p>
  <h3>Question</h3>
  <%= @answer.question.body %>
</p>


<%= link_to 'Edit', edit_answer_path %>