config/routes.rb
Voting::Application.routes.draw do
  
  devise_for :users

  #EDIT ME TO CHANGE ROOT URL
  root :to => 'polls#index'
  
  resources :reports
  
  resources :polls, :shallow => true do
    resources :questions, :shallow => true do
      resources :answers
    end
  end
  
  #for presenting a poll
  match 'polls/:id/present', :to => 'polls#present', :as => :poll_present
  
  #for viewing/manager an active poll
  match 'active_polls/:id', :to => 'active_polls#show', :as => :view_active_poll
  match 'active_polls/:id/next', :to => 'active_polls#next', :as => :next_active_poll
  match 'active_polls/:id/prev', :to => 'active_polls#prev', :as => :prev_active_poll
  
  match ':token/submit/:answer_id', :to => 'active_polls#clicker_submit', :as => :clicker_submit
  
  match ':token', :to => 'active_polls#clicker', :as => :clicker
  
  match 'polls/:id/sort', :to => 'polls#sort', :as => :poll_questions_sort
  
  match 'polls/:poll_id/questions/:q_id/add', :to => 'questions#add_to_poll', :as => :add_to_poll
  match 'polls/:poll_id/questions/:q_id/remove', :to => 'questions#remove_from_poll', :as => :remove_from_poll
  
  match 'active_polls/:id/end', :to => 'active_polls#end', :as => :end_poll  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates :title, 
              :presence => true,
              :length => { :minimum => 5 }
  has_many :reports
  has_many :pollquestions 
  has_many :questions, :through => :pollquestions
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  load_and_authorize_resource
  respond_to :html, :js
  
  # GET /polls
  def index
    @polls.sort! { |a, b| b.created_at <=> a.created_at }
    # This comparison operator is INSANE!
    @active_polls = ActivePoll.all.sort { |a, b| b.report.created_at <=> a.report.created_at }
  end

  # GET /polls/1
  def show
  end

  # GET /polls/new
  def new
  end

  # GET /polls/1/edit
  def edit
  end
  
  # POST: ...
  def sort
    params[:weight].each do |id, weight|
      @pollquestion = @poll.pollquestions.find(id)
      @pollquestion.update_attributes :weight => weight
    end
    respond_with @poll
  end

  # POST /polls
  def create
    if @poll.save
      redirect_to(poll_questions_path(@poll), :notice => 'Poll was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /polls/1
  def update
    if @poll.update_attributes(params[:poll])
      redirect_to(poll_questions_path(@poll), :notice => 'Poll was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /polls/1
  def destroy
    @poll.destroy

    redirect_to(polls_url)
  end
  
  # GET polls/1/present
  # TODO fix failing on not having any questions
  def present
    redirect_to(@poll, :notice => "Must have at least one queston") and return if @poll.questions.count == 0
    
    @active_poll = ActivePoll.new do |a|
      a.poll_id = @poll.id
      a.question_id = Pollquestion.find_all_by_poll_id(@poll.id).min { |a, b| a.weight <=> b.weight }.question.id
    end
    
    report = Report.new do |r|
      r.poll_id = @poll.id
      r.save # might need to do error checking here
    end
    
    @active_poll.report_id = report.id;
    
    if @active_poll.save
      #redirect to the screen to manage the poll from, right now goes to the wrong ActivePoll(pollID)
      redirect_to(view_active_poll_path(@active_poll), :notice => 'Poll is now active for polling.')
    else
      render :action => "show"
    end
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<% content_for :title do %>
  Editing poll
<% end %>

<%= render 'form' %>

app/views/polls/index.html.erb
<% content_for :title do %>
  Listing Polls
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<div class="button-create">
  <%= link_to 'New Poll', new_poll_path %>
</div>

<table class="listing-table polls">
  <tbody>
  <tr>
    <th class="tblcol-name">Title</th>
    <th class="tblcol-link"></th>
    <th class="tblcol-link"></th>
    <th class="tblcol-link last"></th>
  </tr>

<% @polls.each do |poll| %>
  <tr>
    <td class="tblcol-name"><%= poll.title %></td>
    <td class="tblcol-link"><%= link_to 'Show', poll %></td>
    <td class="tblcol-link"><%= link_to 'Edit', edit_poll_path(poll) %></td>
    <td class="tblcol-link last"><%= link_to 'Delete', poll, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
  </tbody>
</table>

<% unless @active_polls.empty? %>
  <h2>Active Polls</h2>
  <table class="listing-table active-polls">
    <tbody>
    <tr>
      <th class="tblcol-name">Title</th>
      <th>Started</th>
      <th class="last">Token</th>
    </tr>
    <% @active_polls.each do |a| %>
      <tr>
        <td class="tblcol-name"><%= link_to a.poll.title, view_active_poll_path(a.id) %></td>
        <td ><%= time_ago_in_words a.report.created_at %> ago</td>
        <td class="token last"><%= a.token %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/polls/new.html.erb
<% content_for :title do %>
  New poll
<% end %>

<%= render 'form' %>

app/views/polls/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'jquery.tablednd_0_5', 'questions' %>
<% end %>

<% content_for :title do %>
  <%= @poll.title %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>



<% if @poll.pollquestions.empty? %>
  <div class="poll-questions-empty">
    No questions.
  </div>
<% else %>
  <%= form_tag({:controller => :polls, :action => "sort"}, :method => "post", :id => "questions-sort", :remote => true) do %>
  <table id="poll-questions">
    <tbody>
      <tr class="nodrop nodrag">
        <th class="tabledrag-handle"></th>
        <th class="question">Questions</th>
        <th class="question-button-show"></th>
        <th class="question-weight">Weight</th>
      </tr>
      <% @poll.pollquestions.sort_by {|q| q.weight}.each do |pq| %>
        <tr>
          <td class="dnd-tab"></td>
          <td class="question"><%= pq.question.body %></td>
          <td class="question-button-show"><%= link_to "Show", question_path(pq.question) %></td>
          <td class="question-weight">
            <%= select_tag("weight[#{pq.id.to_s}]", options_for_select((0..@poll.pollquestions.length - 1).to_a, pq.weight)) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag "Save Order" %>
  <% end %>
<% end %>

<p>
  <%= link_to 'Add questions', poll_questions_path(@poll) %> |
  <%= link_to 'Edit poll title', edit_poll_path(@poll) %> | 
  <%= link_to 'Present poll', poll_present_path %>
</p>

app/views/polls/sort.js.erb
console.log("REMOVE ME: view::sort.js.erb");