config/routes.rb
Voting::Application.routes.draw do
  
  devise_for :users

  #EDIT ME TO CHANGE ROOT URL
  root :to => 'polls#index'
  
  resources :reports
  
  resources :polls, :shallow => true do
    resources :questions, :shallow => true do
      resources :answers
    end
  end
  
  #for presenting a poll
  match 'polls/:id/present', :to => 'polls#present', :as => :poll_present
  
  #for viewing/manager an active poll
  match 'active_polls/:id', :to => 'active_polls#show', :as => :view_active_poll
  match 'active_polls/:id/next', :to => 'active_polls#next', :as => :next_active_poll
  match 'active_polls/:id/prev', :to => 'active_polls#prev', :as => :prev_active_poll
  
  match ':token/submit/:answer_id', :to => 'active_polls#clicker_submit', :as => :clicker_submit
  
  match ':token', :to => 'active_polls#clicker', :as => :clicker
  
  match 'polls/:id/sort', :to => 'polls#sort', :as => :poll_questions_sort
  
  match 'polls/:poll_id/questions/:q_id/add', :to => 'questions#add_to_poll', :as => :add_to_poll
  match 'polls/:poll_id/questions/:q_id/remove', :to => 'questions#remove_from_poll', :as => :remove_from_poll
  
  match 'active_polls/:id/end', :to => 'active_polls#end', :as => :end_poll  
end

app/models/active_poll.rb
class ActivePoll < ActiveRecord::Base
  belongs_to :poll
  belongs_to :question
  belongs_to :report
  belongs_to :user_session
  
  before_create :generate_token
  
  def generate_token    
    o = [('a'..'z')].map{|i| i.to_a}.flatten;  
    token = (0..3).map{ o[rand(o.length)]  }.join;
    while ActivePoll.exists?(["token = ?", token.to_s])
      o = [('a'..'z')].map{|i| i.to_a}.flatten;  
      token = (0..3).map{ o[rand(o.length)]  }.join;
    end
    self.token = token
  end
end

app/controllers/active_polls_controller.rb
class ActivePollsController < ApplicationController
  respond_to :html, :json

  # GET /active_polls/1
  def show
    @active_poll = ActivePoll.find(params[:id])
  end
  
  # GET /active_polls/1/next
  def next
    @active_poll = ActivePoll.find(params[:id])
    currentquestion = Pollquestion.current(@active_poll)

    unless (temp = Pollquestion.next(currentquestion)).nil?
      @active_poll.question = temp.question
      @active_poll.save
    end
   
    redirect_to :action => :show
  end
  
  def prev
    @active_poll = ActivePoll.find(params[:id])
    currentquestion = Pollquestion.current(@active_poll)

    unless (temp = Pollquestion.prev(currentquestion)).nil?
      @active_poll.question = temp.question
      @active_poll.save
    end

    redirect_to :action => :show
  end
      
  # GET /aaaa
  def clicker
    # Active poll being accessed.
    @active_poll = ActivePoll.find_by_token(params[:token])
    
    # Check if user is particpating in this poll. 
    if user_session.active_poll != @active_poll
                    
      # Either user hasn't bound to a poll or their session has expired.
      if user_session.active_poll.nil? || !ActivePoll.exists?(user_session.active_poll)
        # Bind session to active poll.
        user_session.active_poll = @active_poll
        
      else
        # Deal with the cheeky user trying to jump ship... (Redirect?)
      end
    end
    respond_to do |format|
      format.html  { render :layout => 'clicker' }
      format.json  { 
                     data = [ 
                             @active_poll, 
                             @active_poll.question, 
                             @active_poll.question.answers 
                            ];
                     respond_with data.to_json 
                   }
    end
  end
  
  # GET /aaaa/submit/
  def clicker_submit
    redirect_to :action => :clicker and return if user_session.participant.nil? #check if the user has a session or not
    
    @active_poll = ActivePoll.find_by_token(params[:token])
    if AnsweredQuestion.exists?({:question_id => @active_poll.question.id, :participant_id => user_session.participant})
      if @active_poll.question.id == Answer.find(params[:answer_id]).question.id
        AnsweredQuestion.find_by_question_id_and_participant_id(@active_poll.question.id, user_session.participant).update_attributes(:answer_id => params[:answer_id])
        flash[:notice] = "Answer updated."
      else
        flash[:notice] = "That question is no longer being presented."
      end
    else
      AnsweredQuestion.new do |a|
        a.question = @active_poll.question
        a.answer = Answer.find(params[:answer_id])
        a.participant_id = user_session.participant
        a.report_id = @active_poll.report_id
        a.save
        flash[:notice]= "Answer submitted."
      end
    end
    respond_to do |format|
      format.html  { render :layout => 'clicker' }
    end
  end
  
  # GET /active_polls/1/end
  def end
    report = ActivePoll.find(params[:id]).report
    ActivePoll.find(params[:id]).delete
    redirect_to report_path(report)
  end
  
end

app/views/active_polls/_clicker_submit_message.html.erb
<div id="submit_message">
  <h2>Thanks, your answer has been submitted!</h2>
</div>

app/views/active_polls/clicker.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'browser', 'clicker' %>
<% end %>

<% content_for :title do %>
  <%= @active_poll.poll.title %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<div id="container_question">
  <span id="active_poll_id"><%= @active_poll.id %></span>

  <div id="container_question" >
    <h2><%= @active_poll.question.body %></h2>
  </div>

  <div id="answers">
    <ul id="container_answers" >
      <% @active_poll.question.answers.each do |a| %>
        <li class="arrow">
          <%= link_to a.body, clicker_submit_path({:anchor => "pageSubmit", :answer_id => a}), {:class => "answer"} %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div id="reload-question">
  <%= link_to "Click here", clicker_path(@active_poll.token) %> <span id="reload-text">to reload the question.</span>
</div>

app/views/active_polls/clicker.mobile.erb
<% content_for :head do %>
  <%= javascript_include_tag 'mobile', 'clicker' %>
<% end %>

<% content_for :title do %>
  <%= @active_poll.poll.title %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<span id="active_poll_id"><%= @active_poll.id %></span>

<div id="container_question" class="info">
  <h2><%= @active_poll.question.body %></h2>
</div>
<ul id="container_answers" class="rounded">
  <% @active_poll.question.answers.each do |a| %>
    <li class="arrow">
      <%= link_to a.body, clicker_submit_path({:anchor => "pageSubmit", :answer_id => a}), {:class => "answer"} %>
    </li>
  <% end %>
</ul>

<div id="reload-question" class="content">
  <p><%= link_to "Click here", clicker_path(@active_poll.token) %>  <span>to reload the question.</span></p>
</div>

app/views/active_polls/clicker_submit.html.erb
<% content_for :title do %>
  <%= @active_poll.poll.title %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<%= render :partial => "clicker_submit_message" %>

<div id="next-question">
  <%= link_to "Click here", clicker_path(@active_poll.token)%> <span>to change your answer or reload the question.</span>
</div>

app/views/active_polls/clicker_submit.mobile.erb
<% content_for :title do %>
  <span id="active_poll_id"><%= @active_poll.id %></span>
  <%= @active_poll.poll.title %>
<% end %>

<% content_for :title do %>
  <%= @active_poll.poll.title %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<div id="continer_message" class="info">
  <h2>Thanks, your answer has been submitted!</h2>
</div>

<div id="reload-question" class="content">
  <p><%= link_to "Load new question", clicker_path(@active_poll.token) %>  <span>to change your answer or reload the question.</span></p>
</div>

app/views/active_polls/show.html.erb
<% content_for :title do %>
  Active Poll: <%= @active_poll.poll.title %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'pollster' %>
<% end %>

<% content_for :notice do %>
  <%= notice %>
<% end %>

<h3>ID for this poll: <strong><blink><%= @active_poll.token %></blink></strong></h3>

<div class="data">
  <div id="active_poll_id"><%= @active_poll.id %></div>
  <div id="active_question_id"><%= @active_poll.question.id %></div>
</div>


<h2><%= @active_poll.question.body %></h2>

<p>
  <h3>Choices</h3>
  <ol>
    <% @active_poll.question.answers.each do |a| %>
      <li><%= a.body %></li>
    <% end %>
  </ol>
</p>

<p>
  <%= link_to 'Next', next_active_poll_path %> | 
  <!--goto: <%= collection_select :active_poll, :question, @active_poll.poll.questions.all, :to_s, :body %> -->
  <%= link_to 'Previous', prev_active_poll_path %> |
  <%= link_to 'End poll', end_poll_path %>
</p>

<p>
  <%= link_to "View report", report_path %>
</p>